"""add progress fields to index jobs

Revision ID: 0fc113093244
Revises: 8fd81c695992
Create Date: 2026-08-23 00:23:07.933257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0fc113093244'
down_revision: Union[str, None] = '8fd81c695992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_jobs', sa.Column('phase', sa.String(length=30), nullable=True))
    op.add_column('index_jobs', sa.Column('detail', sa.String(length=300), nullable=True))
    op.add_column('index_jobs', sa.Column('progress_current', sa.Integer(), nullable=True))
    op.add_column('index_jobs', sa.Column('progress_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_jobs', 'progress_total')
    op.drop_column('index_jobs', 'progress_current')
    op.drop_column('index_jobs', 'detail')
    op.drop_column('index_jobs', 'phase')
    # ### end Alembic commands ###
