"""add index_jobs queue table

Revision ID: 23a9762258db
Revises: 4c801aa55455
Create Date: 2026-08-22 23:53:02.623309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23a9762258db'
down_revision: Union[str, None] = '4c801aa55455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('files_indexed', sa.Integer(), nullable=True),
    sa.Column('symbols_found', sa.Integer(), nullable=True),
    sa.Column('calls_found', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_jobs_status'), 'index_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_index_jobs_status'), table_name='index_jobs')
    op.drop_table('index_jobs')
    # ### end Alembic commands ###
