"""add users table and link repositories to a user

Revision ID: 4c801aa55455
Revises: 8948793e47b6
Create Date: 2026-08-22 18:32:57.073633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4c801aa55455'
down_revision: Union[str, None] = '8948793e47b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.add_column('repositories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('repositories_github_url_key', 'repositories', type_='unique')
    op.create_unique_constraint(None, 'repositories', ['user_id', 'github_url'])
    op.create_foreign_key(None, 'repositories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_constraint(None, 'repositories', type_='unique')
    op.create_unique_constraint('repositories_github_url_key', 'repositories', ['github_url'])
    op.drop_column('repositories', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
