"""add attempts to index jobs

Revision ID: 8fd81c695992
Revises: 23a9762258db
Create Date: 2026-08-23 00:06:02.044945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8fd81c695992'
down_revision: Union[str, None] = '23a9762258db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; without it the NOT NULL
    # constraint fails on any table that already has data.
    op.add_column(
        'index_jobs',
        sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_jobs', 'attempts')
    # ### end Alembic commands ###
